version: 1
disable_existing_loggers: False
formatters:
        simple:
            format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
    console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: DEBUG
            formatter: simple
            filename: info.log
            maxBytes: 1048576000
            backupCount: 1
            encoding: utf8
    error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: simple
            filename: errors.log
            maxBytes: 1048576000
            backupCount: 1
            encoding: utf8
#    info_file_handler:
#            class: logging.handlers.TimeRotatingFileHandler
#            level: DEBUG
#            formatter: simple
#            filename: info.log
#            when: D
#            encoding: utf8
#            backCount: 1
loggers:
    arialogger:
            level: INFO
            handlers: [info_file_handler,console]
            propagate: no
root:
    level: INFO
    handlers: [console,info_file_handler,error_file_handler]
